version: '3.8'

services:
  db:
    image: postgres:15
    container_name: odoo_postgres
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo_db
      - POSTGRES_PASSWORD=odoo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  odoo:
    image: odoo:18.0
    container_name: odoo_server
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"  # puerto para longpolling si usas chat en vivo u otras funciones en tiempo real
    volumes:
      - ./config/odoo.conf:/etc/odoo/odoo.conf:ro
      - ./custom_addons:/mnt/extra-addons
    entrypoint: ["odoo", "-c", "/etc/odoo/odoo.conf","-d", "odoo", "-u","estate","--dev", "xml"]
    environment:
      - HOST=db
      - USER=odoo_db
      - PASSWORD=odoo_db
    command: >
      --config /etc/odoo/odoo.conf
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"

volumes:
  postgres_data:
  db-data: